//! Sound data: the names of the sounds the client plays for game events ([`builtin`]),
//! looping sounds next to map sprites (`data/sprite_sounds.txt`), NPC voice lookup and sound
//! name resolution. Every sound is one of our files under the asset root (generated by
//! `tools/sfxgen`, music in `content/music`).
//!
//! See `docs/audio.md`.

use crate::FileIndex;

/// Sounds the client plays for game events, by bare name (`.wav` implied, see
/// [`resolve_sound`]). Arrays are variants; one is picked at random each time.
pub mod builtin {
    /// Melee hit landed by an NPC (claws, teeth, fists).
    pub const HIT_UNARMED: [&str; 4] = ["hit_npc_1", "hit_npc_2", "hit_npc_3", "hit_npc_4"];
    /// Melee hit landed by a player with an edged weapon.
    pub const HIT_BLADE: [&str; 4] = ["hit_blade_1", "hit_blade_2", "hit_blade_3", "hit_blade_4"];
    /// Melee hit landed by a player with a blunt weapon (mace, staff, club).
    pub const HIT_BLUNT: [&str; 4] = ["hit_blunt_1", "hit_blunt_2", "hit_blunt_3", "hit_blunt_4"];
    /// Melee results: Miss/Evade, Dodge, Parry; Block picks one of [`BLOCK`].
    pub const MISS: &str = "miss";
    pub const DODGE: &str = "dodge";
    pub const PARRY: &str = "parry";
    pub const BLOCK: [&str; 3] = ["block_1", "block_2", "block_3"];
    /// The local player got hurt.
    pub const PLAYER_HURT: [&str; 3] = ["player_hurt_1", "player_hurt_2", "player_hurt_3"];
    pub const LEVEL_UP: &str = "level_up";
    pub const BUTTON_CLICK: &str = "ui_click";
    pub const TARGET_OPEN: &str = "ui_target";
    pub const WINDOW_OPEN: &str = "ui_window_open";
    pub const WINDOW_CLOSE: &str = "ui_window_close";
    /// Drinking a potion / using an item (the `item_use` spell kit names it too).
    pub const ITEM_USE: &str = "item_use";

    /// Story, gaze and ambience cues the client plays by name (gaze.rs, director_ui.rs,
    /// dialogue.rs, menu, feel.rs, audio/custom.rs). Listed here so tests check them.
    pub const CUES: &[&str] = &[
        "gaze_open",
        "gaze_close",
        "gaze_spot_enter",
        "strain_heartbeat",
        "strain_breath",
        "strain_whisper",
        "strain_overwhelm",
        "cairn_kindle",
        "cairn_rest",
        "quest_accept",
        "quest_progress",
        "quest_complete",
        "dialogue_open",
        "title_sting",
        "end_sting",
        "hit_heavy",
        "amb_open_sky",
        "amb_shelter",
        "amb_eye_open",
        "loop_cairn_fire",
        "foot_dirt_1",
        "foot_dirt_2",
        "foot_dirt_3",
        "foot_dirt_4",
        "foot_stone_1",
        "foot_stone_2",
        "foot_stone_3",
        "foot_stone_4",
    ];

    /// Every event sound above (not the [`CUES`]).
    pub fn all() -> Vec<&'static str> {
        let mut v: Vec<&str> = Vec::new();
        v.extend(HIT_UNARMED);
        v.extend(HIT_BLADE);
        v.extend(HIT_BLUNT);
        v.extend(BLOCK);
        v.extend(PLAYER_HURT);
        v.extend([MISS, DODGE, PARRY, LEVEL_UP, BUTTON_CLICK, TARGET_OPEN, WINDOW_OPEN, WINDOW_CLOSE, ITEM_USE]);
        v
    }
}

/// Where the soundtrack lives (relative to the asset root). Maps without `music=` play all
/// of it.
pub const MUSIC_DIR: &str = "content/music";

/// What [`crate::content::sounds::load`] reads.
#[derive(Debug, Clone, Default)]
pub struct SoundTables {
    /// `data/sprite_sounds.txt`: looping sounds next to map sprites.
    pub sprite_sounds: Vec<SpriteSound>,
    /// File names of the soundtrack ([`MUSIC_DIR`]), sorted.
    pub soundtrack: Vec<String>,
}

/// One line of `data/sprite_sounds.txt`: `sprite sound radius`.
#[derive(Debug, Clone, PartialEq)]
pub struct SpriteSound {
    /// Lowercased sprite file stem; a trailing `*` matches any stem with that prefix.
    pub pattern: String,
    /// Sound file name (`.wav` added to bare names).
    pub sound: String,
    /// Cells; the loop fades linearly from the nearest such sprite to silence at `radius`.
    pub radius: f32,
}

impl SpriteSound {
    /// Whether a map texture name (`CV_Cairn_02.png`) uses this sprite.
    pub fn matches(&self, texture: &str) -> bool {
        let tex = texture.to_lowercase();
        let stem = tex.rsplit_once('.').map_or(tex.as_str(), |s| s.0);
        match self.pattern.strip_suffix('*') {
            Some(prefix) => stem.starts_with(prefix),
            None => stem == self.pattern,
        }
    }
}

/// Parses `data/sprite_sounds.txt` (`#` comments; malformed lines are skipped).
pub fn parse_sprite_sounds(text: &str) -> Vec<SpriteSound> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .filter_map(|l| {
            let v: Vec<&str> = l.split_whitespace().collect();
            let [sprite, sound, radius] = v[..] else { return None };
            let sprite = sprite.to_lowercase();
            let pattern = match sprite.strip_suffix('*') {
                Some(p) => format!("{}*", p.rsplit_once('.').map_or(p, |s| s.0)),
                None => sprite.rsplit_once('.').map_or(sprite.as_str(), |s| s.0).to_string(),
            };
            Some(SpriteSound { pattern, sound: sound_file(sound), radius: radius.parse().ok()? })
        })
        .collect()
}

/// File name of a sound name: bare names are our `.wav` files (`gaze_open` -> `gaze_open.wav`).
pub fn sound_file(name: &str) -> String {
    let name = name.trim();
    if name.contains('.') { name.to_string() } else { format!("{name}.wav") }
}

/// Splits a comma-separated list of sound names, dropping blanks and `0`.
pub fn split_playlist(s: &str) -> Vec<String> {
    s.split(',').map(str::trim).filter(|s| !s.is_empty() && *s != "0").map(str::to_string).collect()
}

/// Asset path (relative to the asset root) of a sound name, bare (`.wav` implied) or with
/// an extension.
pub fn resolve_sound<'a>(index: &'a FileIndex, name: &str) -> Option<&'a str> {
    let name = name.trim();
    if name.is_empty() || name == "0" {
        return None;
    }
    index.resolve(&sound_file(name))
}

/// NPC voice events and the file event names they use.
pub const VOICE_EVENTS: [&str; 4] = ["aggro", "attack", "hit", "death"];

/// Voice lines of an NPC model event: `npc_<model>_<event>.wav` plus `_1`..`_4` variants
/// (one is picked at random). Events: `aggro`, `attack`, `hit` (also `damage`), `death`
/// (also `die`), `greet`. A model without files falls back to its name prefix
/// (`glarewolf_alpha` -> `glarewolf`, `goblin_charger` -> `goblin`).
pub fn voice_lines(index: &FileIndex, model: &str, event: &str) -> Vec<String> {
    let event = match event {
        "damage" => "hit",
        "die" => "death",
        e => e,
    };
    let mut model = model.to_lowercase();
    loop {
        let lines: Vec<String> = std::iter::once(format!("npc_{model}_{event}.wav"))
            .chain((1..=4).map(|i| format!("npc_{model}_{event}_{i}.wav")))
            .filter(|n| resolve_sound(index, n).is_some())
            .collect();
        match model.rsplit_once('_') {
            Some((head, _)) if lines.is_empty() && !head.is_empty() => model = head.to_string(),
            _ => return lines,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_and_playlists() {
        assert_eq!(split_playlist("a.ogg, b.mp3,, 0, "), ["a.ogg", "b.mp3"]);
        assert!(split_playlist(" ").is_empty());
        assert_eq!(sound_file(" gaze_open "), "gaze_open.wav");
        assert_eq!(sound_file("tenebrae.mp3"), "tenebrae.mp3");
        let mut index = FileIndex::default();
        index.insert("miss.wav", "content/sfx/miss.wav");
        assert_eq!(resolve_sound(&index, "miss"), Some("content/sfx/miss.wav"));
        assert_eq!(resolve_sound(&index, "MISS.wav"), Some("content/sfx/miss.wav"));
        assert_eq!(resolve_sound(&index, "old"), None);
        assert_eq!(resolve_sound(&index, "0"), None);
        assert_eq!(builtin::all().len(), 27);
    }

    #[test]
    fn voices_fall_back_to_the_model_prefix() {
        let mut index = FileIndex::default();
        for n in ["npc_glarewolf_hit.wav", "npc_glarewolf_death.wav", "npc_goblin_attack_2.wav", "gaze_open.wav"] {
            index.insert(n, &format!("content/sfx/{n}"));
        }
        assert_eq!(voice_lines(&index, "Glarewolf", "damage"), ["npc_glarewolf_hit.wav"]);
        assert_eq!(voice_lines(&index, "glarewolf_alpha", "die"), ["npc_glarewolf_death.wav"]);
        assert_eq!(voice_lines(&index, "goblin_charger", "attack"), ["npc_goblin_attack_2.wav"]);
        assert!(voice_lines(&index, "cairnkeeper", "greet").is_empty());
        assert!(voice_lines(&index, "spider", "hit").is_empty());
    }

    #[test]
    fn sprite_sounds() {
        let s = parse_sprite_sounds("# c\ncv_cairn* loop_cairn_fire 6\nBrazier.png fire.ogg 3\nbad line\n");
        assert_eq!(s.len(), 2);
        assert_eq!((s[0].pattern.as_str(), s[0].sound.as_str()), ("cv_cairn*", "loop_cairn_fire.wav"));
        assert_eq!(s[1].pattern, "brazier");
        assert!(s[0].matches("CV_Cairn_lit_02.png"));
        assert!(s[1].matches("brazier.png") && !s[1].matches("brazier_2.png"));
    }
}
